In [ ]:
import numpy as np

In [ ]:
n = 8

In [ ]:
adjMat = np.zeros((n + 1, n + 1), dtype = int)

In [ ]:
def addEdgeToMatrix(source, destination):
  adjMat[source][destination] = 1
  adjMat[destination][source] = 1

In [ ]:
addEdgeToMatrix(1, 2)
addEdgeToMatrix(1, 4)
addEdgeToMatrix(2, 3)
addEdgeToMatrix(2, 5)
addEdgeToMatrix(3, 4)
addEdgeToMatrix(3, 6)
addEdgeToMatrix(3, 8)
addEdgeToMatrix(6, 7)

In [ ]:
print(adjMat)

[[0 0 0 0 0 0 0 0 0]
 [0 0 1 0 1 0 0 0 0]
 [0 1 0 1 0 1 0 0 0]
 [0 0 1 0 1 0 1 0 1]
 [0 1 0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 1 0]
 [0 0 0 0 0 0 1 0 0]
 [0 0 0 1 0 0 0 0 0]]


In [ ]:
from queue import Queue

In [ ]:
def bfs(adjMat, source):
  visited = np.zeros(n + 1, dtype = int)
  q = Queue()
  visited[source] = 1
  q.put(source)
  while q.empty() != True:
    u = q.get()
    print(u, end = " ")
    for v in range(len(adjMat[u])):
      if adjMat[u][v] == 1 and visited[v] == 0:
        visited[v] = 1
        q.put(v)

In [ ]:
bfs(adjMat, 1)

1 2 4 3 5 6 8 7 

In [ ]:
from queue import LifoQueue

In [ ]:
def dfs(adjMat, source):
  visited = np.zeros(n + 1, dtype = int)
  stack = LifoQueue()
  visited[source] = 1
  stack.put(source)
  while stack.empty() != True:
    u = stack.get()
    print(u, end = " ")
    for v in range(len(adjMat[u])):
      if adjMat[u][v] == 1 and visited[v] == 0:
        visited[v] = 1
        stack.put(v)

In [ ]:
dfs(adjMat, 1)

1 4 3 8 6 7 2 5 