In [ ]:
import numpy as np

In [ ]:
a_2d = np.array([[1, 2, 3], [4, 5, 6]]) #list inside list
print(a_2d)

[[1 2 3]
 [4 5 6]]


In [ ]:
a_2d = np.zeros((2,3), dtype = int) #row-column must be in a tuple
print(a_2d)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
a_3d = np.zeros((2, 3, 4))
print(a_3d)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [ ]:
a_2d = np.array([[None]*3]*2) #initializing numpy 2d array with None values
print(a_2d)

[[None None None]
 [None None None]]


In [ ]:
a_2d[0][0] = 4
print(a_2d)

[[4 None None]
 [None None None]]


In [ ]:
a_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(len(a_2d))

2


In [ ]:
a_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(a_2d.shape)
print(a_2d.shape[0]) #prints the row
print(a_2d.shape[1]) #prints the column

(2, 3)
2
3


In [ ]:
row, column = a_2d.shape
print(row)
print(column)

2
3


In [ ]:
#Accesing through index
print(a_2d[0][2])

3


In [ ]:
a_2d[0][2] = 9
print(a_2d)

[[1 2 9]
 [4 5 6]]


In [ ]:
#Iterating through 2d array

row, column = a_2d.shape
for i in range(row):
  for j in range(column):
    print(a_2d[i][j])

1
2
9
4
5
6


In [ ]:
#Summing every rows

def rowWiseSum(arr_2d):
  #Complete it by yourself

a_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(rowWiseSum(a_2d))

[ 6 15 24]


In [ ]:
#Summing every columns

def colWiseSum(arr_2d):
  #Complete it by yourself

a_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(colWiseSum(a_2d))

[12 15 18]


In [ ]:
#Swapping columns

def swapCols(arr_2d):
  row, column = arr_2d.shape
  for i in range(row):
    for j in range(int(column/2)):
      temp = arr_2d[i][j]
      arr_2d[i][j] = arr_2d[i][column-1-j]
      arr_2d[i][column-1-j] = temp

  return arr_2d

a_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(swapCols(a_2d))

[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [ ]:
#Swapping rows

def swapRows(arr_2d):
  #Complete it by yourself

a_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(swapRows(a_2d))

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [ ]:
#Adding primary diagonal elements

def addPrimaryDiagonal(arr_2d):
  row, column = arr_2d.shape
  if row != column:
    return "Given array is not a square matrix"
  else:
    sum = 0
    for i in range(row):
      for j in range(column):
        if i == j:
          sum += arr_2d[i][j]
    return sum

a_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(addPrimaryDiagonal(a_2d))

15


In [ ]:
#Adding secondary diagonal elements

def addSecondaryDiagonal(arr_2d):
  #Complete it by yourself

a_2d = np.array([[4, 3, 8], [2, 5, 1], [7, 6, 9]])
print(addSecondaryDiagonal(a_2d))

20
