In [ ]:
import numpy as np

# **Adjacency List**

In [ ]:
class Node:

  def __init__(self, destination, weight):
    self.destination = destination
    self.weight = weight
    self.next = None

In [ ]:
n = 4 #No of Nodes/Vertices

In [ ]:
adjList = np.array([None]*(n + 1)) #Creating an empty adjacency list(array) of n length

In [ ]:
def addEdgetoList(source, destination):
    edge = Node(destination)
    if adjList[source] == None:
        adjList[source] = edge
    else:
        temp = adjList[source]
        while temp.next != None:
            temp = temp.next
        temp.next = edge


In [ ]:
addEdgetoList(1, 2)
addEdgetoList(2, 4)
addEdgetoList(3, 1)
addEdgetoList(3, 4)
addEdgetoList(3, 2)

In [ ]:
def printAdjacencyList(adjList):
    for i in range(len(adjList)):
        temp = adjList[i]
        print(f"{i}: ", end = " ")
        while temp != None:
            print(temp.destination, end = "->")
            temp = temp.next
        print()

In [ ]:
printAdjacencyList(adjList)

0:  
1:  2->
2:  4->
3:  1->4->2->
4:  


# **Adjacency Matrix**

In [ ]:
adjMat = np.zeros((n + 1, n + 1), dtype = int)

In [ ]:
def addEdgetoMatrix(source, destination, weight):
  adjMat[source][destination] = weight
  adjMat[destination][source] = weight

In [ ]:
addEdgetoMatrix(1, 2, 6)
addEdgetoMatrix(2, 4, 3)
addEdgetoMatrix(3, 1, 7)
addEdgetoMatrix(3, 4, 8)
addEdgetoMatrix(3, 2, 1)
addEdgetoMatrix(4, 3, 9)

In [ ]:
print(adjMat)

[[0 0 0 0 0]
 [0 0 6 7 0]
 [0 6 0 1 3]
 [0 7 1 0 9]
 [0 0 3 9 0]]


In [ ]:
#Do the weighted and undirected representation on your own. Also solve the lab problems.